version: '3.2'

services:
  dockcheck-web:
    container_name: dockcheck-web
    hostname: dockcheck-web
    image: palleri/dockcheck-web:latest
    restart: unless-stopped
    ports:
      - '8765:80'
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/dockcheck-web/data:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro      
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.dockcheck-web.rule=Host(`dockcheck.example.com`)
    #  - traefik.http.services.dockcheck-web.loadbalancer.server.port=80
    #  - traefik.docker.network=proxy
    #  # Part for optional traefik middlewares
    #  - traefik.http.routers.dockcheck-web.middlewares=local-ipwhitelist@file,basic-auth@file

#networks:
#  proxy:
#    external: true
